#!/bin/bash

curl -s -o /dev/null 'https://internet.lpu.in/24online/servlet/E24onlineHTTPClient' \
  -X POST \
  -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:145.0) Gecko/20100101 Firefox/145.0' \
  -H 'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8' \
  -H 'Accept-Language: en-US,en;q=0.5' \
  -H 'Accept-Encoding: gzip, deflate, br, zstd' \
  -H 'Content-Type: application/x-www-form-urlencoded' \
  -H 'Origin: https://internet.lpu.in' \
  -H 'Sec-GPC: 1' \
  -H 'Connection: keep-alive' \
  -H 'Referer: https://internet.lpu.in/24online/webpages/client.jsp' \
  -H 'Cookie: _RoomNo=; _Pass=; _UserName=; cf_clearance=CDbHmwKW9yXeHdIRneWqanxIXHDvcu7oqZeJNMkVwts-1764660328-1.2.1.1-FRFElHuFsSo2TnvocJdKHXSv19UtkUzZQDHNowc7UvTkbYGj7GknSfi7AweSdP1q7TpfcwYngmSYYxC7MsiAtNsMHbQUQjvLTKw3newTlmg1KubbEBJdbk.nygGboLm5Jfy3mM.Ng.sWYu57H4..LMZ8AXd8Kl3OdnzAtbmYVD9NlmLaYqxmMm9cpd0jR4L6.Ymv7YAdpcJf3z0dZ9UaDf7O3kw6XufKyDrILlnpbLM' \
  -H 'Upgrade-Insecure-Requests: 1' \
  -H 'Sec-Fetch-Dest: document' \
  -H 'Sec-Fetch-Mode: navigate' \
  -H 'Sec-Fetch-Site: same-origin' \
  -H 'Sec-Fetch-User: ?1' \
  -H 'Priority: u=0, i' \
  --data-raw 'mode=191&isAccessDenied=null&url=null&message=&regusingpinid=&checkClose=1&sessionTimeout=0&guestmsgreq=false&logintype=2&orgSessionTimeout=0&chrome=-1&alerttime=null&timeout=0&popupalert=0&dtold=0&mac=c0%3Adf%3Aed%3Af4%3Ae0%3A59&servername=172.20.0.66&temptype=&selfregpageid=&leave=no&macaddress=c0%3Adf%3Aed%3Af4%3Ae0%3A59&ipaddress=10.35.8.29&username=12311502%40lpu.com&password=Test%4012345&saveinfo=saveinfo&loginotp=false&logincaptcha=false&registeruserotp=false&registercaptcha=false'
